src/br/com/martecs/calcnotas/controller/SessaoController.java
package br.com.martecs.calcnotas.controller;

import java.io.Serializable;

import javax.faces.application.FacesMessage;
import javax.servlet.http.HttpSession;

import org.springframework.context.annotation.Scope;
import org.springframework.context.annotation.ScopedProxyMode;
import org.springframework.security.web.authentication.session.SessionAuthenticationException;
import org.springframework.stereotype.Controller;
import org.springframework.web.context.WebApplicationContext;

import br.com.martecs.calcnotas.pessoa.Usuario;

/**
 * @author V.Camargo
 * 
 * @Date 03 de agosto de 2016
 * @category Session
 * 
 */

@Scope(value = WebApplicationContext.SCOPE_SESSION, proxyMode = ScopedProxyMode.TARGET_CLASS)
@Controller("sessaoController")
public class SessaoController implements Serializable {

    private static final long serialVersionUID = 1L;

    private Usuario usuario;

    public SessaoController() {
    }

    public void atualizaAutorizacao(HttpSession session) {
	try {
	    usuario = (Usuario) session.getAttribute("usuario");
	} catch (SessionAuthenticationException e) {
	    MessageController.geraMensagem(FacesMessage.SEVERITY_ERROR, MessageController.MSG_ERRO_AUTENTICACAO);
	    return;
	}
    }

    public String getNivelAutoridade() {
	if (usuario == null)
	    return null;
	return usuario.getAutoridade().name();
    }

}

WebContent/templates/Layout.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<h:head>

	<f:facet name="first">
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
	</f:facet>

	<title>CalcNotas</title>
	<link rel="shortcut icon"
		href="#{request.contextPath}#{imageConstants.logoICO}"
		id="l_BrowserIcon" />

	<h:outputStylesheet library="martecs" name="styles/custom.css" />
	<h:outputStylesheet library="martecs" name="styles/layout.css" />
	<h:outputStylesheet library="martecs" name="styles/components.css" />

	<h:outputScript target="body" library="primefaces"
		name="jquery/jquery.js" />
	<h:outputScript target="body" library="martecs"
		name="javascripts/app.js" />
</h:head>

<h:body>

	<header class="aw-topbar">
		<h:outputText value="√cN - CalcNotas" styleClass="aw-menu-name" />
		<a style="width: 70px" href="#" class="aw-toggle  js-toggle"><i
			class="fa  fa-bars icon-center" /></a>
	</header>

	<aside class="aw-sidebar  js-sidebar">
		<ui:include src="Menu.xhtml" />
	</aside>

	<section class="aw-content  js-content ">
		<ui:insert name="content" />
	</section>

</h:body>

</html>

WebContent/templates/Menu.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui">

	<nav class="aw-menu ">
		<ul>
			<li id="busca"><h:link outcome="pretty:#{urlConstants.homeURL}">
					<i class="fa  fa-fw  fa-calculator" />Calculadora</h:link></li>

			<li id="ajuda"><h:link outcome="pretty:#{urlConstants.helpURL}">
					<i class="fa  fa-fw  fa-question-circle" />Ajuda</h:link></li>

			<li id="sobre"><h:link outcome="pretty:#{urlConstants.aboutURL}">
					<i class="fa  fa-fw  fa-question" />Sobre</h:link></li>

			<li id="curso"><h:link outcome="#{urlConstants.cursoListURL}"
					rendered="#{sessaoController.nivelAutoridade eq 'ROLE_GERAL'
					or sessaoController.nivelAutoridade eq 'ROLE_ADMIN'}">
					<i class="fa  fa-fw  fa-list-alt" />Cursos</h:link></li>

			<li id="disciplina"><h:link
					outcome="#{urlConstants.disciplinaListURL}"
					rendered="#{sessaoController.nivelAutoridade eq 'ROLE_GERAL' 
					or sessaoController.nivelAutoridade eq 'ROLE_ADMIN' }">
					<i class="fa  fa-fw  fa-book"></i>Disciplinas</h:link></li>

			<li id="curso-disciplina"><h:link
					outcome="#{urlConstants.cursoDisciplinaListURL}"
					rendered="#{sessaoController.nivelAutoridade eq 'ROLE_GERAL'
					or sessaoController.nivelAutoridade eq 'ROLE_ADMIN'}">
					<i class="fa  fa-fw  fa-chain"></i>Disciplina-Curso</h:link></li>

			<li id="user"><h:link outcome="#{urlConstants.usuarioListURL}"
					rendered="#{sessaoController.nivelAutoridade eq 'ROLE_ADMIN'}">
					<i class="fa  fa-fw  fa-user"></i>Usuário</h:link></li>

			<li id="logout"><h:outputLink value="/calcnotas/logout"
					rendered="#{sessaoController.nivelAutoridade eq 'ROLE_GERAL'
					or sessaoController.nivelAutoridade eq 'ROLE_ADMIN'}">
					<i class="fa  fa-fw  fa-power-off"></i>Logout</h:outputLink></li>

		</ul>
	</nav>

</ui:composition>